### ISSUE TITLE
Photos to the About Page

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#19]
Can we add some pictures of kids working to the 'about page'? It seems text heavy. 

Any of these are particularly cute: 
https://www.instagram.com/p/_AAc-5C8Zr/?taken-by=doodlesacademy
https://www.instagram.com/p/-C93B2C8W2/?taken-by=doodlesacademy

And here's another one of me teaching:
https://www.instagram.com/p/9NLsz6i8an/?taken-by=doodlesacademy

I can get even more if you want them!

**Comment by teaboz** [comment]
Actually, revisiting it, I think that those photos and then also the header image should be moved down into the text, and the header replaced with child's art so it is consistent with the rest of the pages.

**Comment by rjsheperd** [comment]
How should this layout look like?

Here's an example of a wireframe by the way. The first is a mobile layout and the second is the regular layout.
[About_Page.pdf](https://github.com/doodlesacademy/doodles/files/169506/About_Page.pdf)

**Comment by rjsheperd** [comment]
Re: the header image, we can certainly change that out.

**Comment by teaboz** [comment]
I think that wireframe looks pretty good--except maybe the slideshow & uppermost image should be switched so the slideshow is at top. 

How about the slideshow be of the particularly cute photos of kids working I sent before, plus the ones I am attaching there. 

The two photos within the text can be the ones of me teaching (the one from the header, the other one I sent above) 

![img_5667](https://cloud.githubusercontent.com/assets/17777336/13708208/253306c0-e762-11e5-96ff-12520efcc1b6.JPG)
![img_6272](https://cloud.githubusercontent.com/assets/17777336/13708207/253300d0-e762-11e5-8138-23bbb91aecdc.JPG)

**Comment by teaboz** [comment]
So, we are moving the marketing video to the top of the about page. 
https://vimeo.com/151472643

Nadja is working on the text for it (use filler text for now, will be done by Saturday). 

Fred is thinking of the design of the text/photos/body of the  something like this: 
http://www.nytimes.com/2016/04/03/business/juicero-juice-system-silicon-valley-interest.html?action=click&contentCollection=Art%20%26%20Design&module=Trending&version=Full&region=Marginalia&pgtype=article

He likes how the text is skinny down the middle with photos hanging off the sides.
