### ISSUE TITLE
PDX Class Page

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#20]
Update PDF to the current version or create it via text (Jason said the PDF looked blurry but it seems fine on my end--this is like the least important part of the site, so whatever is easiest).

**Comment by rjsheperd** [comment]
@teaboz Can you attach PDF here?

**Comment by teaboz** [comment]
Yerp! 
[Art Class Handout COLOR-PPS.pdf](https://github.com/doodlesacademy/doodles/files/169450/Art.Class.Handout.COLOR-PPS.pdf)
