### ISSUE TITLE
Donation Button

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#22]
We have to figure out how we want to add donations. 
I'm suggesting Art.ful.ly because it syncs up with Fractured Atlas, but we can change it when we get 501c3 status without having to switch away, and keep our donor tracking consistent. They have a 'widget' you can create, but I haven't played around with it so don't know if it is any good:

https://www.artful.ly/welcome

**Comment by teaboz** [comment]
name: doodlesacademy@gmail.com
pw: ath7185769811

https://www.artful.ly/widgets/new

**Comment by rjsheperd** [comment]
What do you think of replacing this with the "Support our Kickstarter" once the kickstart campaign goes live?

**Comment by teaboz** [comment]
Kickstarter is mostly for friends/family and colleagues--but we can ask
Alessandra and Jordan what they think.

On Sat, Apr 2, 2016 at 4:56 PM, Richard Sheperd <notifications@github.com>
wrote:

> What do you think of replacing this with the "Support our Kickstarter"
> once the kickstart campaign goes live?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/22#issuecomment-204828766>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by rjsheperd** [comment]
Nice job @phantummm
