### ISSUE TITLE
Import Lesson plans 

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#27]
From PDF version to HTML Version:

Lower Superhero:
https://www.dropbox.com/s/oyubyvzi8usku1o/Lower_SuperheroLessonPacket.pdf?dl=0

Upper Superhero:
https://www.dropbox.com/s/1a8r5s5oimy5o5u/Upper_SuperheroLessonPacket.pdf?dl=0

Lower Symbol & Self:
https://www.dropbox.com/s/6wlk3939d6b3l5r/Lower_Symbol%26Self_LessonPacket.pdf?dl=0

Upper Symbol & Self: 
https://www.dropbox.com/s/z2vvbwp5ldmtirt/Upper_Symbol%26Self_LessonPacket.pdf?dl=0

Lower A Toy's Story: 
https://www.dropbox.com/s/m7mu7fg3gb6aiqm/Lower_Toys%20Story_LessonPacket.pdf?dl=0

Upper A Toy's Story: 
https://www.dropbox.com/s/dspqifyti967y4n/Upper_Toys%20Story_LessonPacket.pdf?dl=0

Lower A Dream Home: 
https://www.dropbox.com/s/mlpy2ibyaahrf60/L.LessonPacket_Dream%20Home.pdf?dl=0

Upper A Dream Home: 
https://www.dropbox.com/s/itsolr8spvrhe8d/U.LessonPacket_Dream%20Home.pdf?dl=0

**Comment by rjsheperd** [comment]
This is done, minus the uploading of images and PDF's
