### ISSUE TITLE
Style Project Pages

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#28]
For next week, please style (code) the project pages that Fred mocked up. I'm starting this issue to put all the docs you need in one place, but @rjsheperd will come in and break it down for you a bit more. 

The templates:
https://dl.dropboxusercontent.com/u/10656919/HTML/home.html

https://dl.dropboxusercontent.com/u/10656919/HTML/lesson_1.html

The info to go in them (it's in Numbers format--let me know if you need a different one (links to image files and so on)) is in the GoogleDrive Tech folder, and is called 'Project Display Map'

@rjsheperd is going to add the text of the lessons from some PDFs that I sent him.

**Comment by rjsheperd** [comment]
TODO: Blockquote for images, Vimeo video
JavaScript to replace Vimeo video with actual video
