### ISSUE TITLE
Coding out educators example page

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#32]
This is not a priority, but we will need a new educators sample page connected to the new site. We'll have to keep paying for the square-space site that it is hosted on until we get one. That being said--not important for the Sunday launch! This is a task for after we get the other shit done that _is_ important for Sunday.  

Here's the current: 
http://www.doodles-academy.org/sample-page-for-educators

Jason, I'm assigning you to this because I know that RJ has been having you do the basic outline of things before he takes over. But I can also assign it to Alex or RJ, just let me know.

**Comment by teaboz** [comment]
This is not linked to on the site, it's what we send to schools/etc. when connecting with them and asking if they might want to partner with us

**Comment by rjsheperd** [comment]
If you want you can use the Pages section of the admin panel to do this. It will generate a URL based off of the title for now, but in the future we can allow you to set your own slug.
