### ISSUE TITLE
Supporters Page

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#33]
Donors should go on top (before portland child art center), and should include:

Laura Harris
Kara Bloom
Kara Larsen

add a header, 'Community Partners' before the PCAS logo and description

Link to our contact page where it says 'use contact page'

**Comment by teaboz** [comment]
Also--don't know if this is possible, but could we have three columns for the donor names so it doesn't look like one long list once we get some more of them?

**Comment by jasonoverby** [comment]
Done!

<img width="1242" alt="screen shot 2016-04-02 at 6 23 46 am" src="https://cloud.githubusercontent.com/assets/13720540/14226621/9bd67c0e-f89b-11e5-9297-b5aa20236190.png">

Curious about styling, though.  Let me know what you think.

**Comment by teaboz** [comment]
Yeah, it looks kind of strange. Do you think it still will once we get more
donors? We are doing the crowdfunding campaign soon, so it will be
relatively soon...

On Sat, Apr 2, 2016 at 6:25 AM, Jason Overby <notifications@github.com>
wrote:

> Done!
>
> [image: screen shot 2016-04-02 at 6 23 46 am]
> <https://cloud.githubusercontent.com/assets/13720540/14226621/9bd67c0e-f89b-11e5-9297-b5aa20236190.png>
>
> Curious about styling, though. Let me know what you think.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/33#issuecomment-204716190>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*
