### ISSUE TITLE
Inspiration image need to expand to full screen when clicked

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#45]

**Comment by teaboz** [comment]
@phantummm @jasonoverby

**Comment by jasonoverby** [comment]
@teaboz @phantummm pretty sure I accomplished a version of this.  I created a pull request for a separate branch for Alex &/or RJ to check to make sure it operates the way it should.  Here is an example:

<img width="1194" alt="screen shot 2016-04-24 at 3 14 33 pm" src="https://cloud.githubusercontent.com/assets/13720540/14770855/52c258ee-0a2f-11e6-968e-4b4593116800.png">

when clicked becomes:

<img width="1207" alt="screen shot 2016-04-24 at 3 14 42 pm" src="https://cloud.githubusercontent.com/assets/13720540/14770858/5d1b6736-0a2f-11e6-89cb-f23842cb7023.png">

Let me know what you think!
