### ISSUE TITLE
Discuss merging subscription/user data models

### ISSUE THREAD

**Issue by phantummm** [doodlesacademy/doodles#47]
Might be good to keep track of mailing-list subscriptions on our side of things.

cc @rjsheperd @teaboz

**Comment by rjsheperd** [comment]
Agreed. I think the other model that I've created but would like to merge at some point is the Member models.

**Comment by phantummm** [comment]
@rjsheperd Sounds good to me. As I've been messing around with the MailChimp integration stuff, it's clear that it will be really nice/powerful if we build out a User/Member/Subscription concept in our data-model, and also something like an Options model to track the various data points that MailChimp uses. As it stands, it's crazy arduous to try to map some form inputs to the simple survey questions on our list-config just using on-the-fly ID-fetching, et cetera.

**Comment by phantummm** [comment]
Ok, so here's how we'll do this:

* Subscribing to the mailing list will create an instance of the `Subscription` class. Creating this record will also hit the MailChimp API and create the subscription there.
* We will keep local records of the "interests" registered with MailChimp (data-points like "location", "how are you involved...", et cetera) as instances of a `SubscriptionOption` class.
* When someone subscribes, we create the `Subscription`, and then send them to an optional form with all the `SubscriptionOption`s. Submitting that form will update the existing `Subscription` locally, and on MailChimp.
* The contact page *will use the same options*. In fact, filling out the contact form and checking the "subscribe me to the list" box will really just create a `Subscription` and attendant `SubscriptionOption` selections in one fell swoop. If they don't check the box, then the contact form just emails to @teaboz without creating the `Subscription` record.

**Comment by rjsheperd** [comment]
Not sure if this may simplify things but rather than create a new subscription option/subscription value, what do you think of using a JsonB store and just dumping the key value pairs in there?

**Comment by rjsheperd** [comment]
Yeah I think that's great. Thanks for taking the time to plan this out. :)

**Comment by phantummm** [comment]
@rjsheperd I feel like those `jsonb` columns are like the sirens trying to sing us to our doom. Very tempting, but I've never known anything but pain from them once any changes are needed. I'd definitely want a good strategy we can stick to so that they don't just turn into thoughtless places to dump whatever.

Plus, JSON columns are a gateway drug that lead inexorably to NoSQL DBs.
