### ISSUE TITLE
Header on the About Page

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#48]
Per Fred: Put the Doodle Logo in the header area of the landing page, put the text that is there under it in two lines so it is centered.

**Comment by jasonoverby** [comment]
@teaboz @fuhred 

Put the logo above the text that starts with "Our Story" or somewhere else?  See screenshot:

<img width="1238" alt="screen shot 2016-04-05 at 5 18 57 am" src="https://cloud.githubusercontent.com/assets/13720540/14281454/205ddc20-faee-11e5-8596-3e5c864d10f9.png">

**Comment by teaboz** [comment]
No, on the landing page. So above 'Students aren't carbon copies...'

On Tuesday, April 5, 2016, Jason Overby <notifications@github.com> wrote:

> @teaboz <https://github.com/teaboz> @fuhred <https://github.com/fuhred>
>
> Put the logo above the text that starts with "Our Story" or somewhere
> else? See screenshot:
>
> [image: screen shot 2016-04-05 at 5 18 57 am]
> <https://cloud.githubusercontent.com/assets/13720540/14281454/205ddc20-faee-11e5-8596-3e5c864d10f9.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/48#issuecomment-205775155>
>


-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
What about this:

<img width="1215" alt="screen shot 2016-04-05 at 10 08 03 am" src="https://cloud.githubusercontent.com/assets/13720540/14291039/5c641d10-fb16-11e5-80d4-6376fcccfee5.png">

**Comment by teaboz** [comment]
@fuhred--what do you think? Is that the size you were thinking?

**Comment by fuhred** [comment]
- 350x350
   - <h2 style="margin-top: *-30*px;"> Students aren't carbon copies.</h2>
   - remove the quotation mark from the second line

thanks!

**Comment by jasonoverby** [comment]
@fuhred were you wanting to add or remove space b/w elements by changing "-10" to the margin to "-30"? Reason I ask is "-30" is too much, but I could do "-20"

**Comment by jasonoverby** [comment]
@fuhred How about now:

<img width="1116" alt="screen shot 2016-04-05 at 10 23 01 am" src="https://cloud.githubusercontent.com/assets/13720540/14291424/6a5188de-fb18-11e5-8a40-a8c83a7eba1f.png">

**Comment by fuhred** [comment]
yes, i would like to reduce the space between the logo and the copy. why is
-30 too much when -20 is ok?

**Comment by jasonoverby** [comment]
It all changed when I resized the image.  Here is -65, which I think looks good, but let me know if you'd like there to be slightly more or less space:

<img width="1217" alt="screen shot 2016-04-05 at 10 31 22 am" src="https://cloud.githubusercontent.com/assets/13720540/14291722/affef7f8-fb19-11e5-8deb-9fd6248a0163.png">

**Comment by fuhred** [comment]
oh interesting! I am just messing around with it with Chrome's Inspect
feature.

can you give more space? approx 1.5x the existing space. (right now it
reads too much as part of the logo). thanks!

**Comment by jasonoverby** [comment]
This is -50:

<img width="1223" alt="screen shot 2016-04-05 at 10 44 27 am" src="https://cloud.githubusercontent.com/assets/13720540/14292109/7082f168-fb1b-11e5-820b-bd1af5a4d13f.png">

**Comment by fuhred** [comment]
looks good. thanks jason!

**Comment by jasonoverby** [comment]
Word up!

**Comment by teaboz** [comment]
Hurrah!
