### ISSUE TITLE
Change Red button on Landing Page

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#49]
Change the red button on the landing page that says 'go to projects' (red=stop, just not the best color for it). Any other color from the brand book is fine. 

https://drive.google.com/file/d/0B7Rpxamrcq2NM1YzaXlvZENBcVE/view?usp=sharing

**Comment by jasonoverby** [comment]
Fixed!

**Comment by teaboz** [comment]
Nice choice. I think that blue is everyone's favorite color out of the bunch @fuhred
