### ISSUE TITLE
Mailchimp Signup Integration

### ISSUE THREAD

**Issue by rjsheperd** [doodlesacademy/doodles#5]
@phantummm Do you think we should do this on the FE or BE?

**Comment by teaboz** [comment]
COuld we also have a pop-up while people are accessing the projects saying something like 'Sign up to receive notifications when there is a new project available'

**Comment by teaboz** [comment]
Change the text for the bottom newsletter sign up to say something like 'Stay in touch! Sign up to be notified of new projects & organization updates. '

**Comment by phantummm** [comment]
Relevant discussion here: https://github.com/doodlesacademy/doodles/issues/47

Basic integration is working now, and I can pretty easily add a followup (optional) form for adding first and last names. However, adding the rest of the form fields from the contact page will be more complicated, as discussed in the issue linked above.

Should we leave it as a plain-old email signup for now, until we get some more data-model stuff figured out? Or should I go with the first-and-last-name additional info form?

cc. @teaboz @rjsheperd

**Comment by phantummm** [comment]
Another possible solution for the short term would be: user enters email, clicks subscribe button, and is then forwarded to the Contact page, with the email pre-populated. They fill it out, it sends the info to Tempest, who can manually enter it in MailChimp to keep track of the data.

This is far from optimal, obvs. But I would help with the manual entry if a ton of people sign up, and it would be a stop-gap until we get the data-model built out.

Thoughts?

**Comment by teaboz** [comment]
@phantummm I'm concerned with the second option not because of the work, but because people might not follow through the whole way and we would lose the lead. Is there a way to capture their email when they enter it and send it over to mailchimp, then have a popup come up with the email pre-filled out and the other stuff available for them to fill out? Mailchimp will just update their info if they do fill out the extra stuff, but we would already have their email if they chose not to.

**Comment by rjsheperd** [comment]
@teaboz can you point me in the direction of the Mailchimp login? I might
be able to take a look at this over my lunch break.

**Comment by teaboz** [comment]
DoodlesAcademy, Ath7185769811! (or ath7185769811, or Ath7185769811)

**Comment by phantummm** [comment]
Merged intermediate fix. Closing this ticket in favor of ticket about full data-model: https://github.com/doodlesacademy/doodles/issues/47
