### ISSUE TITLE
Quotes Area

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#50]
1) Can we put a circle photo of people in the testimonials—fake until we get real photos--like the photos on the mock up version

2) change the picture to light grey (the picture is being used on another page)

3) not italicized

**Comment by jasonoverby** [comment]
@teaboz In this area? 
<img width="1170" alt="screen shot 2016-04-07 at 5 25 00 am" src="https://cloud.githubusercontent.com/assets/13720540/14350919/213cfd80-fc81-11e5-85c9-67c71be3a784.png">

**Comment by teaboz** [comment]
Yep. And by picture I meant the background picture--just make it a light gray band.

**Comment by jasonoverby** [comment]
What about this:

<img width="1208" alt="screen shot 2016-04-08 at 5 35 16 am" src="https://cloud.githubusercontent.com/assets/13720540/14383734/cd088a9c-fd4b-11e5-84f5-b483bda169ad.png">

It's going to be a bit complicated (requires javascript) to have the image change as the quote changes, but I'm sure it can be done.  

I also think it looks nice w/out the image:

<img width="1200" alt="screen shot 2016-04-08 at 5 37 53 am" src="https://cloud.githubusercontent.com/assets/13720540/14383782/199a3766-fd4c-11e5-8e33-3bbe0e385f3a.png">

**Comment by teaboz** [comment]
Try that same light grey:

CMYK 12, 9, 8, 0

RGB 221, 222, 224

HEX #DDDEE0

@fred, see Jason's questions irt image.

On Fri, Apr 8, 2016 at 5:38 AM, Jason Overby <notifications@github.com>
wrote:

> What about this:
>
> [image: screen shot 2016-04-08 at 5 35 16 am]
> <https://cloud.githubusercontent.com/assets/13720540/14383734/cd088a9c-fd4b-11e5-84f5-b483bda169ad.png>
>
> It's going to be a bit complicated (requires javascript) to have the image
> change as the quote changes, but I'm sure it can be done.
>
> I also think it looks nice w/out the image:
>
> [image: screen shot 2016-04-08 at 5 37 53 am]
> <https://cloud.githubusercontent.com/assets/13720540/14383782/199a3766-fd4c-11e5-8e33-3bbe0e385f3a.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/50#issuecomment-207416139>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
harder to read with a lighter grey if we leave the text white:

<img width="1132" alt="screen shot 2016-04-08 at 7 34 31 am" src="https://cloud.githubusercontent.com/assets/13720540/14387080/7ea96914-fd5c-11e5-8fed-090b8bb41bfb.png">

and a darker color for text still doesn't look great to me:

<img width="1130" alt="screen shot 2016-04-08 at 7 34 11 am" src="https://cloud.githubusercontent.com/assets/13720540/14387064/6e9cc37c-fd5c-11e5-9d0a-a8924e15c97e.png">

**Comment by teaboz** [comment]
@fuhred: what do you think?

**Comment by fuhred** [comment]
I like the darker gray background. Once you figure out how to integrate the
photo, I think there are two ways to go for format:

1) if the image stays where it is, the quote and name should be
left-aligned with some more space between the photo and the text than there
currently is, or
2) the image on top, and quote and name remain center-aligned

**Comment by jasonoverby** [comment]
@teaboz changed to the darker gray background

When you have images for the sayers of the quotes I should be able to add those
