### ISSUE TITLE
additional text on artwork quilt

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#51]
on the landing page, in the artwork quilt, include the text 'Artwork from Near & Far project' underneath so it is clear that the artwork is all from the same project

**Comment by jasonoverby** [comment]
Like this:

<img width="933" alt="screen shot 2016-04-05 at 6 01 57 am" src="https://cloud.githubusercontent.com/assets/13720540/14282615/0d5ec246-faf4-11e5-92a8-7afb25cf1020.png">

**Comment by teaboz** [comment]
Yep. Can we make it one size smaller?

On Tuesday, April 5, 2016, Jason Overby <notifications@github.com> wrote:

> Like this:
>
> [image: screen shot 2016-04-05 at 6 01 57 am]
> <https://cloud.githubusercontent.com/assets/13720540/14282615/0d5ec246-faf4-11e5-92a8-7afb25cf1020.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/51#issuecomment-205792098>
>


-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
Yep:

<img width="988" alt="screen shot 2016-04-05 at 7 01 41 am" src="https://cloud.githubusercontent.com/assets/13720540/14284411/4f3b2c92-fafc-11e5-8e69-3546c3cd08b0.png">

**Comment by teaboz** [comment]
Perfect!
