### ISSUE TITLE
Minor changes to Lesson Pages

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#52]
1)Above H1 there should be a thin grey line
2) Inspiration, Introduction, Worktime, Cleanup should all be numbered 1,2,3,4
3) Put the time back on the header line, and even if they can’t be different formats, just differentiate with a comma

**Comment by jasonoverby** [comment]
Number 1 is done:

<img width="1075" alt="screen shot 2016-04-05 at 6 20 15 am" src="https://cloud.githubusercontent.com/assets/13720540/14283158/ef149ed4-faf6-11e5-855c-3137343ac286.png">

Re 2: I think those are reflecting the markdown below.  You would need to change the markdown for each lesson & add numbers (but it would change the text in the body as well) - @rjsheperd is that correct?

@teaboz could you show me an example of what you mean on 3?

**Comment by fuhred** [comment]
Re 3: right now the minutes estimated per section are on their own separate
line (because different formatting can't exist on the same line?). the
introduction section takes 5 minutes, so the heading should say
INTRODUCTION, 5m, even if they can't be formatted differently.

**Comment by jasonoverby** [comment]
Oh, I see.  I think that is also something that would have to be changed in the markdown for each lesson.  Unfortunately I am unable to access the admin panel at the moment so I can't check this theory. @rjsheperd ?

**Comment by jasonoverby** [comment]
@fuhred @tempest verified that this is indeed the case.  

For **2** Trying to work this out.  I'll keep working on it, but this is the best I've been able to manage:
<img width="1008" alt="screen shot 2016-04-06 at 6 18 18 am" src="https://cloud.githubusercontent.com/assets/13720540/14317945/7cb46346-fbbf-11e5-9b18-d2402635ce47.png">
@rjsheperd is there a way to target just the second line of this?

For **3** Moving the required times to the same lines as the headings in the markdown will accomplish what you need.

**Comment by jasonoverby** [comment]
@rjsheperd @teaboz @fuhred 
Worked it out:

<img width="1156" alt="screen shot 2016-04-06 at 7 49 30 am" src="https://cloud.githubusercontent.com/assets/13720540/14321004/435de6d2-fbcc-11e5-86c0-525bcd5de3d7.png">

**Comment by teaboz** [comment]
@jasonoverby: I have to go through each lesson page today to make sure it is accurate, so I'll change the minutes to the same line on the existing lessons since it has to be done manually. Is there a way to add that to the general page template, though, so that in the future it doesn't have to be done manually?

**Comment by jasonoverby** [comment]
@teaboz There is a way to eventually add that to the template, but @phantummm and I would need to work that out.

**Comment by teaboz** [comment]
Closing this b/c the only thing left is the minutes and that has proven to be a bigger issue with it's own ticket.
