### ISSUE TITLE
Buttons on 'About Page'

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#53]
Per Nadja's suggestion: can we add two bands to the bottom of the 'about page'? Just like on the landing page. One that has a button in it saying saying 'lessons' and the other the donate button copied from page 1?

Nadja made the point that if someone goes all the way down, they would probably be interested.

**Comment by jasonoverby** [comment]
Done!  Copied exactly, but would you rather change any text, etc?

**Comment by teaboz** [comment]
Yeah, I think we should make them briefer. Let's say that the lessons can
just say: We make high-quality art education easy. And then the
button--skipping th other text. Also--could we add a band of color (even
just grey?) to differentiate it from the text above?
For the donate, let's just have the part that says: Donations help us
develop and offer our free classes and free online curriculum, bringing
quality art education to students everywhere., then the donate button.

On Thu, Apr 7, 2016 at 5:18 AM, Jason Overby <notifications@github.com>
wrote:

> Done! Copied exactly, but would you rather change any text, etc?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/53#issuecomment-206847430>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
Got it.  See below (3 separate images).  Let me know about further styling.  I added a white margin b/w the sections & changed the text above the lessons area from a headline to a paragraph tag, but it would be easy to adjust those.

<img width="1060" alt="screen shot 2016-04-08 at 4 33 21 am" src="https://cloud.githubusercontent.com/assets/13720540/14382499/2ac60bcc-fd43-11e5-91e8-6bfedb9207d8.png">
<img width="1049" alt="screen shot 2016-04-08 at 4 33 29 am" src="https://cloud.githubusercontent.com/assets/13720540/14382503/30f23714-fd43-11e5-886c-619e5daf1aa3.png">
<img width="1045" alt="screen shot 2016-04-08 at 4 33 37 am" src="https://cloud.githubusercontent.com/assets/13720540/14382505/35bb49d4-fd43-11e5-84eb-e888a7274c39.png">

**Comment by teaboz** [comment]
I like the text choices here (smaller), but it looks like they are big on
the site itself.

Can we also try a really light grey--try this from the brand book: CMYK 12,
9, 8, 0

RGB 221, 222, 224

HEX #DDDEE0

Also--on the site itself the donation area is white, not green, on the
about page

On Fri, Apr 8, 2016 at 4:36 AM, Jason Overby <notifications@github.com>
wrote:

> Got it. See below (3 separate images). Let me know about further styling.
> I added a white margin b/w the sections & changed the text above the
> lessons area from a headline to a paragraph tag, but it would be easy to
> adjust those.
>
> [image: screen shot 2016-04-08 at 4 33 21 am]
> <https://cloud.githubusercontent.com/assets/13720540/14382499/2ac60bcc-fd43-11e5-91e8-6bfedb9207d8.png>
> [image: screen shot 2016-04-08 at 4 33 29 am]
> <https://cloud.githubusercontent.com/assets/13720540/14382503/30f23714-fd43-11e5-886c-619e5daf1aa3.png>
> [image: screen shot 2016-04-08 at 4 33 37 am]
> <https://cloud.githubusercontent.com/assets/13720540/14382505/35bb49d4-fd43-11e5-84eb-e888a7274c39.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/53#issuecomment-207394746>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by teaboz** [comment]
@jasonoverby: IRT the donate and Lesson Plan buttons…what if we eliminated the text ltogether? So just two buttons? I feel like that might be cleaner.

![mockup](https://cloud.githubusercontent.com/assets/17777336/14386365/4281f9c2-fd59-11e5-935f-41b98d3654d9.jpg)

**Comment by jasonoverby** [comment]
like this?

<img width="1179" alt="screen shot 2016-04-08 at 7 44 25 am" src="https://cloud.githubusercontent.com/assets/13720540/14387328/c0934ace-fd5d-11e5-84f5-6f0fabc73e0d.png">

**Comment by teaboz** [comment]
Yeah. I think that looks great!

On Fri, Apr 8, 2016 at 7:45 AM, Jason Overby <notifications@github.com>
wrote:

> like this?
>
> [image: screen shot 2016-04-08 at 7 44 25 am]
> <https://cloud.githubusercontent.com/assets/13720540/14387328/c0934ace-fd5d-11e5-84f5-6f0fabc73e0d.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/53#issuecomment-207459564>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
Cool!  Updated on site!
