### ISSUE TITLE
Add site-wide flash/message-display for error state

### ISSUE THREAD

**Issue by phantummm** [doodlesacademy/doodles#64]
Since we're dealing with some user-input, and will be dealing with more in the future, we need to add a message flash for displaying error/success messages as feedback.

@fuhred @rjsheperd @teaboz Let's make it look siiiiiick.

**Comment by teaboz** [comment]
So we need a design that says something like "your message was saved" or,
"Sorry, there was an error"

On Wed, Apr 6, 2016 at 1:21 AM, Alex Hunley <notifications@github.com>
wrote:

> Since we're dealing with some user-input, and will be dealing with more in
> the future, we need to add a message flash for displaying error/success
> messages as feedback.
>
> @fuhred <https://github.com/fuhred> @rjsheperd
> <https://github.com/rjsheperd> @teaboz <https://github.com/teaboz> Let's
> make it look siiiiiick.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/64>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by phantummm** [comment]
Examples of flash messages:

![image](https://cloud.githubusercontent.com/assets/2888017/14320943/f5c3b104-fbcb-11e5-980e-1f04fd0ff6b2.png)

![image](https://cloud.githubusercontent.com/assets/2888017/14320953/0647491e-fbcc-11e5-8ee9-416c976f43e3.png)
