### ISSUE TITLE
Question: why auto-deploy from Github?

### ISSUE THREAD

**Issue by phantummm** [doodlesacademy/doodles#68]
@rjsheperd I've run into a couple situations now where us using the auto-deploy from `master` feature on Heroku has confused me. Are you married to this way of doing things? I'm not super-opinionated about it, just wondering what the pros are. The biggest cons that I've noticed are:

1. Checking compiled assets into Git. Gross! :mask: 
2. Not getting the console output from the deploy process, which adds a couple [non-interactive] steps to debugging deployment problems.

Like I say, not totally against it, just wondering what the case for it is.

cc. @jasonoverby

**Comment by rjsheperd** [comment]
I'm not totally married to it, but I do think it gets us as close to
continuous delivery as I can see us managing at the moment. If you think
there's a way to support continuous delivery differently, I'm all ears. :)

**Comment by phantummm** [comment]
@rjsheperd Fair point. I guess I'm not clear on the pros of continuous delivery for a project this size, given the pain-points I mentioned. It seems like Heroku deploys aren't any more complicated than pushing to Github. The one thing I do think is nice about it is having the defined, one-way pipeline of: Local –> Github –> Heroku, as opposed to Local –> Github && Local –> Heroku.

I'll look into allowing Heroku handle the asset-compilation from the Github integration, as the compiled assets is the biggest bummer for me. There might be a way to have Heroku send deploy-logs to Slack, too, which would help with the second point.
