### ISSUE TITLE
Copy Editing

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#72]
We have someone going through and copy-editing the text. I'm going to make the edits to the project pages/pages I have access to, but I don't have access to all. So these are the edits I cannot make (there will be a round two when he's done--sorry, I know it's not exciting work).: 

HOME PAGE and FOOTER:

1)
“Our mission is to expand children's access to high-quality arts education; we work to remove barriers for educators, and strive to make it easy to offer excellence.”

The semicolon seems stilted, and unnecessarily complicates the relationship between the two clauses. Consider making it two straightforward sentences:

“Our mission is to expand children's access to high-quality arts education. We work to remove barriers for educators, and strive to make it easy to offer excellence.”

2)
“Art lessons that inspire real creativity.”

Every other statement on the page is rendered as a complete sentence (subject/verb/object), but this is not. It’s a bit disconcerting. Consider something like:

“Challenging art lessons inspire real creativity” or similar.

3)
“Doodles Academy brings art education to more students.”
“More” is a comparative term—more than what?
How about:
“Doodles Academy brings art education to underserved students.” That sets up the next sentence nicely. 

4)

“With no art classes at her school, my daughter was floundering – always sketching, but frustrated by her lack of direction … We are grateful for the excellent guidance provided by Doodles Academy, which has filled a void in our daughter’s life.”
 
Eliminate the spaces before and after the em dash, and the space before (but not after) the ellipsis:

“With no art classes at her school, my daughter was floundering–always sketching, but frustrated by her lack of direction... We are grateful for the excellent guidance provided by Doodles Academy, which has filled a void in our daughter’s life.”

5)
"The online art classes provided by Doodles Academy are invaluable to me as a homeschool mom and teacher. … I also appreciated the flexibility of the program. We can adjust it to our life, schedule, and health."

Ask Erin if it’s okay to change “appreciated” to “appreciate” in her quote (or just change it—will she care?) Also, there should be no space or other character before the ellipsis (between the first and second sentences).  One space after (as it is now) is correct.

"The online art classes provided by Doodles Academy are invaluable to me as a homeschool mom and teacher... I also appreciate the flexibility of the program. We can adjust it to our life, schedule, and health."

Another option is to delete the ellipses altogether and just set the text as consecutive sentences. That would be easier to absorb quickly, and it wouldn’t distort the writer’s meaning.

6)
“Our vision is that every child receives an arts education that inspires and rewards student creativity, growth and problem solving, irrespective of school budget, zip code, or student demographics.”
Consider changing to:
“Our vision is that every child receives an arts education that inspires and rewards creativity...”

7)
“Donations help us develop and offer our free classes and free online curriculum, bringing quality art education to students everywhere.”
 
Elsewhere on the page, there are three references to “high-quality art education.” Make this reference consistent with those? Or, to avoid repetitiveness. use a synonymous word or phrase (such as “dynamic”) 

8)
Stay in touch! Sign up to be notified of new projects & organization updates.
No reason for the “&” here, and it’s distracting—change to “and”

9)
Doodles Academy is a non-profit organization fiscally sponsored by Fractured Atlas 

MW says “nonprofit,” which is what most nonprofits use these days. 

ABOUT US:
1)
Founder Tempest NeuCollins received an MFA from the School of Visual Arts in New York City. Through her varied teaching experience from private classes to charter school classrooms, she became frustrated that so much art education is incredibly costly and individualized or over-crowded with little opportunity for differentiation. She became determined to find a way to offer an affordable, open-ended curriculum that would bring art education to more students.

The “from...to...” construction implies a range or spectrum, but it might not be obvious to a given reader what that range is. Consider changing these two conjunctions to:

Founder Tempest NeuCollins received an MFA from the School of Visual Arts in New York City. Through her varied teaching experience in private classes and charter school classrooms, she became frustrated that so much art education is incredibly costly and individualized or overcrowded with little opportunity for differentiation. She became determined to find a way to offer an affordable, open-ended curriculum that would bring art education to more students.

2)
“Overcrowded” is not hyphenated.
3)
Also, isn’t “individualized” education generally seen as a good (if “costly”) thing? Is there another word that implies inefficiency without the upside of “individualized”?

4)
“Designed to be used in any educational context--from the homeschooler's living room to the public school classroom--the Doodles curriculum...

Use em dashes, not double hyphens:

“Designed to be used in any educational context—from the homeschooler's living room to the public school classroom—the Doodles curriculum...”

5)
“They include samples images, timelines, instructional videos for students, and demo videos for educators...”

Change to sample

PROJECTS:

In “What are units”:
1)
“However [add comma] by following the units in order, students experience a scaffolded learning structure, gradually adding complexity without overwhelming students. By the end of the 2016 school year, there will be over a years worth of weekly, scaffolded art lessons.”

The subject of the first sentence shifts from “students” to “learning structure”—confusing. Better is:

However, by following the units in order, students experience a scaffolded learning structure that gradually adds complexity without overwhelming them. By the end of the 2016 school year, there will be over a year’s worth of weekly, scaffolded art lessons.

Also, “years” should be “year’s”

**Comment by teaboz** [comment]
Here's the remainder: 

SUPPORTERS:

1)

“Community Supporters” is in title case (initial caps) whereas “donors” and 

“community partners” are all l/c; then back to initial caps for “Portland Child Art 

Studio.”

Use initial caps also for “Donors” and “Community Partners”?

2)

Elsewhere (including their website) Portland Child Art Studio is not prefaced by 

“the,” so I would delete it from:

“The Portland Child Art Studio is dedicated to supporting the perceptual 

development of children through artistic learning.”

3) lifelong, not life-long (MW)

4) “Through them, we are able to workshop our projects in actual classes before 

they are offered online.”

Use the organization’s name (or abbreviation—PCAS) instead of “them”? Because at 

this point it’s been a few lines since the last direct reference, besides which we’re 

now into a new paragraph. 

TEAM:

1)

Should we use “Board of Directors” instead of “The Board”? I’m not sure...

2) [Jason Overby]

“programmer, front and back-end”

An interesting case, in which the convention (one word run together, two words, or 

hyphen) hasn’t been clearly established in the online literature. I’m seeing all three 

forms in use. 

If we stay with the hyphenated form (which we use for Alex [“back-end”]), then we 

would want: “programmer, front- and back-end” with a hyphen (then a space) 

after “front.” 

Or delete the hyphen: “programmer, front and back end.” I prefer the 

latter—cleaner—but then we need to change Alex to “back end.” In any case I will 

note in the style sheet that it is an issue to be resolved.

3) Stephen Maine is your “copy editor,” not “copy-editor.” 

4) Maile Thiesen is identified by the work she does (“film editing” rather than her 

position or function (which I guess would be “film editor”) as everyone else is. 

5) these positions or functions are given in title case (initial caps) through and 

including Fred, then inexplicably change to all l/c beginning with Alex, through to 

the end (Maile).  Should be consistent.

PDX CLASS

1)

We are assuming the typical user knows what PDX means. 

2) again, is it “Portland Child Art Studio” or “the Portland Child Art Studio”?

(“the PCAS studio space” is fine because we are referring to “the... studio space”)

3) “Portland Community” should be “Portland community” (unless the “Portland 

Community” is in widespread use out there in the, um... Portland community.

4) change “class size is very limited” to “class size is limited.” (Either it’s limited or 

it’s unlimited.)

5) There are numerous inconsistencies in the “Available Classes” box, which are 

obvious when you look closely. 

I suggest this format:

Monday: Lower Academy, 4:00–4:45  

colon after the day; comma after “Academy”; en dash meaning “to”; use 

hour:minutes (i.e., “4:00” not “4”)

6)

In THE PROGRAM box:

Period (not comma) after “June”

DONATE

1) “nonprofit”, not “non-profit”

2) “tax deductible” not “tax-deductible” (MW)

**Comment by teaboz** [comment]
Lesson 1, the Synopsis "Under “Lesson 1”

1)
...each superhero had his or her own unique backstory that told who they were,...
Use present tense?
...each superhero has his or her own unique backstory that tells who they are,...

2)
Overview/Synopsis repeats Creating a Backstory verbatim. If that is intended, make the above change (#1) here as well
"

**Comment by jasonoverby** [comment]
@teaboz Are you planning to change the above w/r/t lessons in the markdown?

I have changed almost everything else listed above that.  A few notes and exceptions:

- **About Us**: "individualized" has been changed to "inefficient".  Let me know if you are cool with that.
- **Team**: "The Board" has been changed to "Board of Directors".  It seems more professional.  Let me know if that is alright.
- **Team**: titles are now all lowercase.
- **PDX Class**: to make changes to the "Available Classes" and "THE PROGRAM" boxes you would need to change the pdf.  Alternatively, @phantummm and I should eventually just redo that content as html, but it can't happen right away.
- **DONATE**: @phantummm for the life of me I can't find where this text is to change it.  Have any ideas?

**Comment by teaboz** [comment]
@jasonoverby 
I can't access the synopsis section in markdown. I have to go through all the lessons and delete the synopsis that is included in markdown, because it is also included as text at the top (not in markdown) so it repeats weirdly.

**Comment by jasonoverby** [comment]
@teaboz I'll take another look at that.

**Comment by teaboz** [comment]
@jasonoverby: the rest of the edits/notes seem fine, thanks!

**Comment by jasonoverby** [comment]
Of course!

**Comment by jasonoverby** [comment]
@teaboz so you just removed the synopsis from the lesson, correct?

**Comment by teaboz** [comment]
I did, but I wonder if that was a mistake, because now it disappeared in both places! As well as the inspiration image and video...

**Comment by jasonoverby** [comment]
Did you adjust anything else?  Was this only on lower academy creating a back story?

**Comment by teaboz** [comment]
Both upper and lower 'Creating a Backstory'. 

I adjusted some stylistic things--moving the time up to the same line, making sure things were italicized correctly, and adding Stephen's copy-edit suggestions

**Comment by jasonoverby** [comment]
Gotcha - I had copied the text for the Lower Academy earlier & by pasting it in as before it fixed it so that inspo image appears & there is a space for the video (but it is saying that video does not exist).  I had not copied the text for Upper Academy - do you have that? I think a very specific structure was created that has to be adhered to or it will break things like the inspo & video links, but that's just an assumption.  RJ would know for sure.

**Comment by teaboz** [comment]
Student artists learn to recognize shapes and types of lines as they design and draw their own superheroes.  They begin by creating a book that tells the backstory of their superhero using their choice of drawing, writing, or a combination. They then move on to isolating graphic images into basic curved lines and using a handout to copy disparate parts of a superhero into their own unique character. They create this silhouette onto their final paper which will become the cover to their book. They learn about how costumes and details are another way of telling parts of the story, which they add to their superhero. They finish by completing their superheroes with pan watercolors.

**Comment by teaboz** [comment]
@jasonoverby: did I just break it again? all I did was move the minutes up to the line with the header area

**Comment by teaboz** [comment]
I think I'm not understanding, sorry

**Comment by teaboz** [comment]
So I can't make stylistic edits? Can I make edits to the content?

**Comment by jasonoverby** [comment]
Call me

**Comment by teaboz** [comment]
@rjsheperd: see above. We're not making stylistic (css) changes per @fuhred until we hear from you if that might be the reason things are breaking and how to prevent that.

**Comment by teaboz** [comment]
specifically, we were trying to delete the synopsis from the lesson plans because it shows up twice (once by the example image and once in the text) and we were trying to move the times within the lesson plan to the same line as the 1./2./3./4. sections

**Comment by teaboz** [comment]
Just to make things more clear, I'm going to close this ticket, but open a new one specifically for the stylistic changes.
