### ISSUE TITLE
Button on Lesson Overviews

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#74]
@fuhred 

I think we talked about this, but I'm not sure it made it in the final design. We're trying to figure out a way to prioritize the overview part of the Project pages rather than the Standards (hence the grey background there is a another ticket out for). Would it be easy to add a button under the photocopies/copyright info that separates the top from the standards and says 'Lesson 1' or something similar? A button just like the ones at the bottom of the individual lesson pages. 

Also, not sure how I feel about the expletives (Wow! Amazing!) before the lesson buttons on the lesson pages themselves. I think a simple 'Lesson 1, Lesson 2' would do the trick. @fuhred: opinion?

**Comment by fuhred** [comment]
In my mockup there was a "Lesson 1" button on the Overview page right where
you just proposed. Jason that should be easy to add right?

[image: Inline image 1]


I think the tone of *Wow! and Amazing!* is inconsistent with the rest of
the site, so I think those should be striked. But I do think "Lesson X
finished!" or something else congratulatory would be good.

**Comment by jasonoverby** [comment]
@teaboz @fuhred Unfortunately the site is not set up to allow me to add a button in that spot.  We should chat about a better structure for adding content to the project overviews & lesson plans and then @phantummm and I can refactor that aspect of the site.

I removed the congratulatory words so that it just reads "Lesson X finished!" at the bottom.

**Comment by teaboz** [comment]
Argh. Ok. So far 1)button 2)captions 3)time stamp for lessons (right? am I
forgetting anything?)

On Sun, Apr 17, 2016 at 7:27 AM, Jason Overby <notifications@github.com>
wrote:

> @teaboz <https://github.com/teaboz> @fuhred <https://github.com/fuhred>
> Unfortunately the site is not set up to allow me to add a button in that
> spot. We should chat about a better structure for adding content to the
> project overviews & lesson plans and then @phantummm
> <https://github.com/phantummm> and I can refactor that aspect of the site.
>
> I removed the congratulatory words so that it just reads "Lesson X
> finished!" at the bottom.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/74#issuecomment-211028665>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to expand children's access to high-quality arts education.
We work to remove barriers for educators, and strive to make it easy to
offer excellence.*
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
@teaboz Word.  I created a separate issue for your list, etc.  Closing this issue...
