### ISSUE TITLE
Stylistic Changes to the Lessons

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#75]
1) the synopsis from the lesson plans shows up twice (once by the example image and once in the text) 
2) move the times within the lesson plan to the same line as the 1./2./3./4. sections
3) Move the Inspiration Image below, rather than above, the header  "LOOK AND DISCUSS AN ART PIECE THAT INTRODUCES SOME OF THE LESSON CONCEPTS."

**Comment by jasonoverby** [comment]
@phantummm look at lesson.rb

I see how to make it so that synopsis can be deleted and insp img & video will still appear, but I don't think there's a way to do that & still include the synopsis at the top.

@teaboz Would it be preferable to have it as is (with synopsis listed twice) or to only have synopsis in the section below (which I can make happen)?

**Comment by teaboz** [comment]
@jason: preferable to have it twice, I think, otherwise there's a big empty
space at the top

On Mon, Apr 11, 2016 at 5:13 AM, Jason Overby <notifications@github.com>
wrote:

> @phantummm <https://github.com/phantummm> look at lesson.rb
>
> I see how to make it so that synopsis can be deleted and insp img & video
> will still appear, but I don't think there's a way to do that & still
> include the synopsis at the top.
>
> @teaboz <https://github.com/teaboz> Would it be preferable to have it as
> is (with synopsis listed twice) or to only have synopsis in the section
> below (which I can make happen)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/75#issuecomment-208312095>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to provide the tools necessary for art lessons that inspire
students to meet their creative potential. *
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*
