### ISSUE TITLE
Goofy looking citations

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#78]
The citations under the inspiration images look goofy because they are all jumbled together. Can we put a break between the description and the Title?

**Comment by jasonoverby** [comment]
I can do this:
<img width="1189" alt="screen shot 2016-04-14 at 4 28 16 am" src="https://cloud.githubusercontent.com/assets/13720540/14536400/0dfc4fae-0227-11e6-9aed-a7f1a40bcb4f.png">

For anything more, it would be best to add a inspiration_image_title to the data model.  @phantummm can we chat about that tonight?  I tried to do it on my own, but I was unsuccessful.

**Comment by teaboz** [comment]
That's way better than it was!

On Thu, Apr 14, 2016 at 9:59 AM, Jason Overby <notifications@github.com>
wrote:

> I can do this:
> [image: screen shot 2016-04-14 at 4 28 16 am]
> <https://cloud.githubusercontent.com/assets/13720540/14536400/0dfc4fae-0227-11e6-9aed-a7f1a40bcb4f.png>
>
> For anything more, it would be best to add a inspiration_image_title to
> the data model. @phantummm <https://github.com/phantummm> can we chat
> about that tonight? I tried to do it on my own, but I was unsuccessful.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/78#issuecomment-210048598>
>



-- 
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to expand children's access to high-quality arts education.
We work to remove barriers for educators, and strive to make it easy to
offer excellence.*
*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
Cool!  I switched all of them to be that way!

**Comment by jasonoverby** [comment]
Actually, like this:
<img width="1059" alt="screen shot 2016-04-14 at 11 41 58 am" src="https://cloud.githubusercontent.com/assets/13720540/14539579/d5bafcf8-0235-11e6-9ec3-f3a25b22b56b.png">

**Comment by teaboz** [comment]
Hurrah!
