### ISSUE TITLE
change wording on front page

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#79]
'art lessons that inspire real creativity' 

rather than 

'challenging art lessons inspire real creativity'

**Comment by jasonoverby** [comment]
Did you want:
"_art lessons **that** inspire real creativity_" 
**or**
"_art lessons inspire real creativity_"

Were you wanting just to remove the word "_**Challenging**_" or change the sentence?  I ask b/c "_art lessons **that** inspire real creativity_" is not a complete sentence.

**Comment by teaboz** [comment]
Mostly the goal is just to remove the word challenging...Nadja thought the word might be challenging for people.

**Comment by jasonoverby** [comment]
Now that I look at it "art lessons **that** inspire real creativity" makes more sense in context.  Done!
