### ISSUE TITLE
Minor changes to Supports Page

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#80]
@fuhred had some feedback: 

1) "View available classes here" is missing a link

2) Change "If you are interested in signing up for a class, please use our contact page." to "
"If you are interested in signing up for a class, please visit the PDX Class page." With link 

3)  the donation list should start at the left of the screen (under the donors) rather than being centered

**Comment by jasonoverby** [comment]
This one is done

**Comment by teaboz** [comment]
Hurrah! Crossing them off....

**Comment by jasonoverby** [comment]
Yes!






On Thu, Apr 14, 2016 at 6:59 AM -0700, "teaboz" <notifications@github.com> wrote:












Hurrah! Crossing them off....
