### ISSUE TITLE
Refactor admin pages for project & lesson creation

### ISSUE THREAD

**Issue by jasonoverby** [doodlesacademy/doodles#81]
Here is the initial wish list from @teaboz 

- button to jump to lesson 1 before "Standards" on project overview page. @phantummm I'm thinking we would want to have two larger text fields for the markdown, one for project overview & one for standards)
- 2-3 input fields for image captions (title, artist?, description)
- time stamp for lessons
- removing the "Synopsis" within the "Overview"

@fuhred or anyone, can you think of others?

**Comment by jasonoverby** [comment]
5. move the times within the lesson plan to the same line as the 1./2./3./4. sections
6. move the duration of each part of the lesson to its own line
7. Move the Inspiration Image below, rather than above, the header "LOOK AND DISCUSS AN ART PIECE THAT INTRODUCES SOME OF THE LESSON CONCEPTS."

**Comment by jasonoverby** [comment]
1. On the 'project page' eliminate 'Skills'
2. On the 'project page' Setup rather than Set Up

**Comment by jasonoverby** [comment]
Format:

# Overview
## Synopsis


## Objective

## Setup
Students will be working individually and choosing their own materials, so have materials set up in a way that is easy to pass out as well as easy for the students artists to see and select from. 

## Materials

## Photocopies

## Media

# Lesson
## Inspiration, *10m*
### LOOK AND DISCUSS AN ART PIECE THAT INTRODUCES SOME OF THE LESSON CONCEPTS.

Project the inspiration image where students can see it. Give students a moment to study it silently, then begin a brief discussion with the phrase, “What can we find?”. Paraphrase what students say for the benefit of the class, being careful to remain neutral, then ask, “What else can we find?” 

Alternatively, allow them to draw or write what they notice on a blank piece of paper or in a sketchbook.

*<sub><sup>The point of this discussion time is to have students learn and add onto each other’s thoughts. By remaining neutral and simply repeating what students say you allow students to do the heavy mental lifting and also create an environment where there is no wrong answer, fostering creativity and mental risk-taking.  </sub></sup>


## Introduction, *5m*
### WATCH THE VIDEO INTRODUCTION


### CHECK FOR UNDERSTANDING
Check for understanding by asking, “Who was listening closely that can sum up what we are doing today?” Make sure that student artists can list all the steps and clarify anything that needs clarifying. 

## Worktime, *20-25m*
### INDEPENDENT

The students work independently on their work as the teacher circulates.  Foster strong work habits by commenting on student artists who are focused on their work as well as student artists who seem to be pushing themselves to try new things.

### FOCUS ON 
 
 


## Clean-up/Presentations, *5-10m*
### STUDENTS DISCUSS THE ARTISTIC DECISIONS THAT THEY MADE USING ‘WHAT, HOW, AND WHY” THEN TAKE COMMENTS OR QUESTIONS. 

Depending on the teacher’s style of classroom management, it might be helpful to only choose and train a few kids to clean. The rest of the class can be busy with the presentation. Make sure to train these helpers well in advance so that you aren’t left with a messy room. 

Clean-up times will vary with materials; get to know your class and allow 5-10 minutes depending on how efficient they are and whether or not the material was messy. 

Choose presenting student artists in advance and let them know during their work time so that they are prepared. Sharing should work as follows:
Student stands by their work. A teacher should hold it, or place it on an easel. 

The student presents their work, answering What they made, How they made it, and Why they made the decisions that they did. When they are done they ask, “Any comments or questions?” and can take responses from the audience. 

A note on responses: it is o.k. if a audience member questions or wants clarification from the artist. It is also o.k. if an audience member makes suggestions. But it must be done in a kind, thoughtful, and respectful way. 

Always end the conversation by asking the class to give the artist a compliment.

# Extension
## Anticipated Problems


## Early Finishers

**Comment by jasonoverby** [comment]
- grey box around the standards on the overview page

**Comment by teaboz** [comment]
Inspiration Image expanding to full screen when clicked

**Comment by fuhred** [comment]
long-term wish list: standards to first show in a collapsed state, and when
clicked to expand (like "code" and "documentation" here:
https://standards.usa.gov/labels/)

**Comment by jasonoverby** [comment]
@teaboz 

I created a new pull request for Alex to review which changed the basic markdown structure & added a field within lessons for a lesson_description that can take the place of the synopsis.  I made it so the markdown can be left as is on already existing lessons (so those will not have to be rebuilt) while allowing new lessons to be entered in a way more in accordance with what you'd like to see.

This is a kind of test for a way we could refactor the way lessons are built for the entire site while leaving alone the existing data so that you don't have to re-enter all lessons.

**Comment by teaboz** [comment]
Sounds promising!

On Wed, May 11, 2016 at 5:14 PM, Jason Overby <notifications@github.com>
wrote:

> @teaboz <https://github.com/teaboz>
>
> I created a new pull request for Alex to review which changed the basic
> markdown structure & added a field within lessons for a lesson_description
> that can take the place of the synopsis. I made it so the markdown can be
> left as is on already existing lessons (so those will not have to be
> rebuilt) while allowing new lessons to be entered in a way more in
> accordance with what you'd like to see.
>
> This is a kind of test for a way we could refactor the way lessons are
> built for the entire site while leaving alone the existing data so that you
> don't have to re-enter all lessons.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/doodlesacademy/doodles/issues/81#issuecomment-218626677>
>



-- 
...
*DONATE TO OUR FUNDRAISER
<https://www.generosity.com/education-fundraising/every-child-deserves-a-space-to-doodle>
TO
SUPPORT QUALITY ART LESSONS FOR KIDS, EVERYWHERE. *
...
Tempest NeuCollins
*Executive Director*
*...*
*Our mission is to expand children's access to high-quality arts
education. *

*Instagram <https://instagram.com/doodlesacademy/> & **Facebook
<https://www.facebook.com/DoodlesAcademy> *
*doodles-academy.org <http://doodles-academy.org>*
*tempest@doodles-academy.org <tempest@doodles-academy.org>*

**Comment by jasonoverby** [comment]
Add delete button for lessons

**Comment by jasonoverby** [comment]
If Alex doesn't get a chance to show you we can look at it together next Thurs...

**Comment by phantummm** [comment]
This was done by @jasonoverby ...with gusto!
