### ISSUE TITLE
Adding Donors from 5/12-5/17

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#82]
Attached is the donor list from 5/12-5/17. Add first and last name. File in Slack (wouldn't let me export CVS here). Kara Bloom is already on as a donor. 

Might make sense to put them alphabetically to make sure we don't list people twice if they donate in the future?

**Comment by jasonoverby** [comment]
@teaboz I created a donor model that should allow you to enter donors via the admin panel.  Since this is more complicated than simple HTML/CSS I created a separate branch for Alex and/or RJ to check before implementing on the live site.

**Comment by teaboz** [comment]
Awesome! It occurred to me on the flight home--would it be possible to make donations of $100 or more bold? I know that they didn't want separate categories yet, but it seems like there should be some differentiation. If that's complication, no big deal, and forget-about-it.

**Comment by jasonoverby** [comment]
Yep - totally possible.  Once this gets pushed to the site we can decide for sure.






On Sun, Apr 24, 2016 at 5:41 PM -0700, "teaboz" <notifications@github.com> wrote:












Awesome! It occurred to me on the flight home--would it be possible to make donations of $100 or more bold? I know that they didn't want separate categories yet, but it seems like there should be some differentiation. If that's complication, no big deal, and forget-about-it.

**Comment by teaboz** [comment]
Great! Alex is going to try to get to it tonight.

(by the way--awesome job rocking out on this. I might be wrong given my total ignorance of how coding works, but this feels next level)

**Comment by jasonoverby** [comment]
Thanks!  Super satisfying to see it work!






On Sun, Apr 24, 2016 at 5:43 PM -0700, "teaboz" <notifications@github.com> wrote:












Great! Alex is going to try to get to it tonight.



(by the way--awesome job rocking out on this. I might be wrong given my total ignorance of how coding works, but this feels next level)

**Comment by teaboz** [comment]
WIshlist: 3 columns, alphabetized so we can easily see if they’ve already donated, and then a secret slot to keep track of how much people have donated (not visible) and bolded if they donated over 100

**Comment by teaboz** [comment]
Could we also change the header to read 'supporters' instead of 'community supporters?'. I think that makes more sense since donations are coming from everywhere.

**Comment by jasonoverby** [comment]
All of this is now done except having supporters who donate more than 100 in bold.  It will take a second to work on that.  What I was thinking of doing was to simply add a checkbox to the donor creation in the admin so that when checked the name would appear in bold.  Does that sound good?  Alternatively, I could add a box for you to record how much they donated (which will only be visible in the admin) that will cause the name of anyone who donated more than a certain amount to appear in bold.

**Comment by jasonoverby** [comment]
Also, still working on alphabetizing.

**Comment by teaboz** [comment]
Either would be fine--but I'm thinking maybe the second would be better, only because then if/when we get high-level donors and Jordan and Alessandra want to create additional tiers, we would already have it set up for that. But, the checkbox is also totally works, just thinking ahead.

**Comment by jasonoverby** [comment]
add to donor model
- middle name
- donated amount
- suffix (Jr., etc.)
- title (Dr. etc.)
