### ISSUE TITLE
Minor text change to Mission Statement

### ISSUE THREAD

**Issue by teaboz** [doodlesacademy/doodles#87]
The board voted to adjust the mission/vision slightly, so we should update it under the video on the front page. 

New:
Our mission is to expand children's access to high-quality arts education. 

Our vision is that every child receives an arts education that inspires and rewards creativity, growth and problem solving, irrespective of cost or zip code.

**Comment by jasonoverby** [comment]
Done!
<img width="1180" alt="screen shot 2016-05-05 at 5 37 49 am" src="https://cloud.githubusercontent.com/assets/13720540/15043644/8d7a97ce-1283-11e6-978a-21c3d4f1b71c.png">

**Comment by teaboz** [comment]
Hurrah!
